sudo: required
language: node_js
services:
  - docker

before_install:
  - docker-compose -f ./docker-compose.travis.yml up -d node
  - docker-compose -f ./docker-compose.travis.yml logs

install: true